# <font color = lightcoral>Sequence Matching Finalize
>

## <font color = grey> Admin

In [1]:
import pandas as pd
import os
import gzip
import time
import warnings
import os
import shutil
from datetime import datetime
import time
# Set display option to show the full length of the column
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

# Determine the base directory based on the effective user ID
if os.geteuid() == 0:  # root user
    base_dir = '/root'
else:
    base_dir = '/home/sagemaker-user'

# Set the environment variable
os.environ['BASE_DIR'] = base_dir

# Verify the base directory
print(f"Base directory set to: {base_dir}")

import warnings
warnings.simplefilter("ignore")

Base directory set to: /home/sagemaker-user

---

# <font color = lightsteelblue> 4 Key Files

In [2]:
import pandas as pd
import time

data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04A.Local_Data_Files'

################################## Part 1: Parsed Raw File ###################################

print("\n" + "*"*100)
print("********************** Part1 1: Parsed Raw File ******************************************")
print("*"*100 + "\n")

parsed_file =  f"{data_dir}/BGL.log_structured.csv"
parsed_file_df = pd.read_csv(parsed_file)
display(parsed_file_df.head())
print("Shape of Parsed Raw File:", parsed_file_df.shape)

######################### Part 2: Encoded File with Feature for Model Training  ######################

print("\n" + "*"*100)
print("********************** Part 2:  Input Data with Features ******************************************")
print("*"*100 + "\n")

encoded_feature_input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
encoded_feature_input_file_df = pd.read_parquet(encoded_feature_input_file)
display(encoded_feature_input_file_df.iloc[:, :20].head())
print("Shape of Encoded File with Features:", encoded_feature_input_file_df.shape)

# ######################### Part 3: Event_ID to Template Mapping  #######################################

print("\n" + "*"*100)
print("********************** Part 3: Event_ID to Template Mapping ******************************************")
print("*"*100 + "\n")

eventid_template_file = f"{data_dir}/20240711_Template_to_EventID_Mapping_v1.00.csv"
eventid_template_df = pd.read_csv(eventid_template_file)
display(eventid_template_df.head())
print("Shape of Event_ID to Template Mapping:", eventid_template_df.shape)

# ######################### Part 4: Event_ID to Encoding Mapping  #######################################

print("\n" + "*"*100)
print("********************** Part 4:  Event_ID to Encoding Mapping ******************************************")
print("*"*100 + "\n")

eventid_encoding_file = f"{data_dir}/20240711_EventID_to_EncodedInteger_Mapping_v1.00.csv"
eventid_encoding_df = pd.read_csv(eventid_encoding_file)
display(eventid_encoding_df.head())
print("Shape of Event_ID to Encoding Mapping:", eventid_encoding_df.shape)

****************************************************************************************************
********************** Part1 1: Parsed Raw File ******************************************
****************************************************************************************************

,LineId,Label,Id,Date,Code1,Time,Code2,Component1,Component2,Level,Content,EventId,EventTemplate
0,1,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.363779,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
1,2,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.527847,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
2,3,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.675872,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
3,4,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.823719,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
4,5,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.982731,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected

Shape of Parsed Raw File: (4713493, 13)

****************************************************************************************************
********************** Part 2:  Input Data with Features ******************************************
****************************************************************************************************

,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count,EventId_1,EventId_2
4,2005-06-03 16:00:00,4,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0,228,228
5,2005-06-03 16:05:00,5,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0,729,987
6,2005-06-03 16:10:00,6,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0,734,430
7,2005-06-03 16:15:00,7,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0,987,987
8,2005-06-03 16:25:00,9,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0,95,504

Shape of Encoded File with Features: (14537, 35451)

****************************************************************************************************
********************** Part 3: Event_ID to Template Mapping ******************************************
****************************************************************************************************

,EventId,EventTemplate,Occurrences
0,3aa50e45,instruction cache parity error corrected,105924
1,b9250ad9,MidplaneSwitchController performing bit sparing on R<*>-M<*>-L<*>-U<*>-C bit <*>,964
2,fc5f0940,generating core.<*>,1706751
3,1840cbfe,"<*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*>",33939
4,828a502b,<*> <*> <*> error(s) (dcr <*>) detected and corrected,5040

Shape of Event_ID to Template Mapping: (1000, 3)

****************************************************************************************************
********************** Part 4:  Event_ID to Encoding Mapping ******************************************
****************************************************************************************************

    EventId  EncodedValue
0  0025df56             0
1  0045c3a8             1
2  004a68ba             2
3  00980b01             3
4  00d49120             4

Shape of Event_ID to Encoding Mapping: (1000, 2)

---

# <font color = red> Reset sequence for original parquet file

In [7]:
import pandas as pd

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04A.Local_Data_Files'
input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
output_file = f"{data_dir}/20240714_final_input_file_reset_sequence_v1.00.parquet"

# Load data
encoded_feature_input_file_df = pd.read_parquet(input_file)

# Reset the sequence numbers starting from 0
encoded_feature_input_file_df.reset_index(drop=True, inplace=True)
encoded_feature_input_file_df['Seq_Num'] = encoded_feature_input_file_df.index

# Update the 'time_start_int' column to start from 0
encoded_feature_input_file_df['time_start_int'] = encoded_feature_input_file_df.index

# Move the 'Seq_Num' column to the first position
cols = encoded_feature_input_file_df.columns.tolist()
cols = ['Seq_Num', 'time_start_int'] + [col for col in cols if col not in ['Seq_Num', 'time_start_int']]
encoded_feature_input_file_df = encoded_feature_input_file_df[cols]

# Save the updated DataFrame to a new parquet file
encoded_feature_input_file_df.to_parquet(output_file)

# Display the first few rows of the updated data
print("\n" + "*"*100)
print("********************** Updated Input Data with Features ******************************************")
print("*"*100 + "\n")
display(encoded_feature_input_file_df.iloc[:, :20].head())
print("Shape of Updated File with Features:", encoded_feature_input_file_df.shape)

# Print the minimum and maximum sequence numbers and the total number of records
min_seq_num = encoded_feature_input_file_df['Seq_Num'].min()
max_seq_num = encoded_feature_input_file_df['Seq_Num'].max()
total_records = len(encoded_feature_input_file_df)

print("\n" + "*"*100)
print("********************** Sequence Number Info ******************************************")
print("*"*100 + "\n")
print(f"Minimum Seq_Num: {min_seq_num}")
print(f"Maximum Seq_Num: {max_seq_num}")
print(f"Total number of records: {total_records}")

****************************************************************************************************
********************** Updated Input Data with Features ******************************************
****************************************************************************************************

,Seq_Num,time_start_int,time_start,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count,EventId_1
0,0,0,2005-06-03 16:00:00,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0,228
1,1,1,2005-06-03 16:05:00,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0,729
2,2,2,2005-06-03 16:10:00,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0,734
3,3,3,2005-06-03 16:15:00,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0,987
4,4,4,2005-06-03 16:25:00,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0,95

Shape of Updated File with Features: (14537, 35452)

****************************************************************************************************
********************** Sequence Number Info ******************************************
****************************************************************************************************

Minimum Seq_Num: 0
Maximum Seq_Num: 14536
Total number of records: 14537

# <font color = blue> Review New Mapping File (from orig to seq)

In [3]:
import pandas as pd

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
input_file = f"{data_dir}/20240714_225943_orig_input_w_seq_mapping_master.parquet"

# Load data
encoded_feature_input_file_df = pd.read_parquet(input_file)

# Display the first 20 columns of the first few rows
print("\n" + "*"*100)
print("********************** Head ******************************************")
print("*"*100 + "\n")
display(encoded_feature_input_file_df.iloc[:, :20].head())

# Display the last 20 columns of the last few rows
print("\n" + "*"*100)
print("********************** Tail ******************************************")
print("*"*100 + "\n")
display(encoded_feature_input_file_df.iloc[:, :20].tail())

# Display records from sequence 11600 to 11630 with only the first 20 columns
print("\n" + "*"*100)
print("********************** Train Test Transition ******************************************")
print("*"*100 + "\n")
records_11600_to_11630 = encoded_feature_input_file_df.iloc[11600:11631, :20]
display(records_11600_to_11630)

# Print the minimum and maximum sequence numbers and the total number of records
min_seq_num = encoded_feature_input_file_df['Seq_Num'].min()
max_seq_num = encoded_feature_input_file_df['Seq_Num'].max()
total_records = len(encoded_feature_input_file_df)

print("\n" + "*"*100)
print("********************** Sequence Number Info ******************************************")
print("*"*100 + "\n")
print(f"Minimum Seq_Num: {min_seq_num}")
print(f"Maximum Seq_Num: {max_seq_num}")
print(f"Total number of records: {total_records}")

****************************************************************************************************
********************** Head ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
0,4,Train,2005-06-03 16:00:00,4,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0
1,5,Train,2005-06-03 16:05:00,5,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0
2,6,Train,2005-06-03 16:10:00,6,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0
3,7,Train,2005-06-03 16:15:00,7,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0
4,8,Train,2005-06-03 16:25:00,9,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0

****************************************************************************************************
********************** Tail ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
14532,14536,Test,2006-01-04 07:35:00,61823,0,1,606,0,0.000000,7,2,1,35433,4.0,0.0,0,0.693147,-0.693147,53.0,18.0
14533,14537,Test,2006-01-04 07:40:00,61824,0,6,156,5,1.609438,7,2,10,35431,1.0,0.5,0,0.000000,1.609438,48.0,18.0
14534,14538,Test,2006-01-04 07:45:00,61825,0,2,193,1,0.693147,7,2,2,35433,10.0,0.5,0,1.609438,-0.916291,49.0,19.0
14535,14539,Test,2006-01-04 07:50:00,61826,0,3,156,2,1.039721,7,2,4,35433,2.0,0.5,0,0.693147,0.346574,21.0,19.0
14536,14540,Test,2006-01-04 08:00:00,61828,1,1,99,0,0.000000,8,2,8,35433,4.0,0.0,0,1.039721,-1.039721,25.0,18.0

****************************************************************************************************
********************** Train Test Transition ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
11600,11604,Train,2005-11-08 13:50:00,45482,0,1,738,0,0.000000,13,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1043.0,12.0
11601,11605,Train,2005-11-08 14:00:00,45484,0,1,176,0,0.000000,14,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1036.0,12.0
11602,11606,Train,2005-11-08 14:10:00,45486,0,1,68,0,0.000000,14,1,13,35433,1.0,0.000000,0,0.000000,0.000000,1048.0,12.0
11603,11607,Train,2005-11-08 14:20:00,45488,0,1,68,0,0.000000,14,1,1,35433,13.0,0.000000,0,0.000000,0.000000,17.0,10.0
11604,11608,Train,2005-11-08 14:30:00,45490,0,3,108,2,0.483611,14,1,2910,35433,1.0,0.000687,0,0.000000,0.483611,2926.0,12.0
11605,11609,Train,2005-11-08 14:35:00,45491,0,2,108,1,0.029707,14,1,1714,35433,2910.0,0.000583,0,0.483611,-0.453904,4639.0,13.0
11606,11610,Train,2005-11-08 14:40:00,45492,0,2,108,1,0.348832,14,1,4608,35433,1714.0,0.000217,0,0.029707,0.319125,9246.0,14.0
11607,11611,Train,2005-11-08 15:05:00,45497,0,1,638,0,0.000000,15,1,16,35433,4608.0,0.000000,0,0.348832,-0.348832,9249.0,14.0
11608,11612,Train,2005-11-08 15:10:00,45498,0,2,68,1,0.693147,15,1,16,35433,16.0,0.062500,0,0.000000,0.693147,9264.0,15.0
11609,11613,Train,2005-11-08 15:15:00,45499,0,1,638,0,0.000000,15,1,8,35433,16.0,0.000000,0,0.693147,-0.693147,6362.0,13.0
11610,11614,Train,2005-11-08 15:25:00,45501,0,1,763,0,0.000000,15,1,3,35433,8.0,0.000000,0,0.000000,0.000000,4651.0,12.0
11611,11615,Test,2005-11-08 15:35:00,45503,0,1,638,0,0.000000,15,1,8,35433,3.0,0.000000,0,0.000000,0.000000,51.0,11.0
11612,11616,Test,2005-11-08 15:40:00,45504,0,1,68,0,0.000000,15,1,8,35433,8.0,0.000000,0,0.000000,0.000000,43.0,11.0
11613,11617,Test,2005-11-08 15:55:00,45507,0,1,68,0,0.000000,15,1,1,35433,8.0,0.000000,0,0.000000,0.000000,28.0,10.0
11614,11618,Test,2005-11-08 16:05:00,45509,0,1,68,0,0.000000,16,1,8,35433,1.0,0.000000,0,0.000000,0.000000,28.0,10.0
11615,11619,Test,2005-11-08 16:10:00,45510,0,1,68,0,0.000000,16,1,1,35433,8.0,0.000000,0,0.000000,0.000000,26.0,10.0
11616,11620,Test,2005-11-08 16:30:00,45514,0,4,399,9,1.251989,16,1,15,35433,1.0,0.600000,1,0.000000,1.251989,33.0,13.0
11617,11621,Test,2005-11-08 16:55:00,45519,0,1,176,0,0.000000,16,1,1,35433,15.0,0.000000,0,1.251989,-1.251989,26.0,13.0
11618,11622,Test,2005-11-08 17:25:00,45525,1,2,74,1,0.693147,17,1,1024,35433,1.0,0.000977,0,0.000000,0.693147,1049.0,14.0
11619,11623,Test,2005-11-08 17:30:00,45526,0,1,176,0,0.000000,17,1,1,35433,1024.0,0.000000,0,0.693147,-0.693147,1042.0,14.0
11620,11624,Test,2005-11-08 17:45:00,45529,0,1,68,0,0.000000,17,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1042.0,14.0
11621,11625,Test,2005-11-08 18:25:00,45537,0,3,95,2,1.098612,18,1,3,35433,1.0,0.666667,1,0.000000,1.098612,1030.0,13.0
11622,11626,Test,2005-11-08 18:35:00,45539,0,1,68,0,0.000000,18,1,2,35433,3.0,0.000000,0,1.098612,-1.098612,1031.0,13.0
11623,11627,Test,2005-11-08 18:40:00,45540,0,1,228,0,0.000000,18,1,1,35433,2.0,0.000000,0,0.000000,0.000000,8.0,12.0
11624,11628,Test,2005-11-08 18:50:00,45542,0,2,68,1,0.500402,18,1,10,35433,1.0,0.100000,0,0.000000,0.500402,17.0,13.0
11625,11629,Test,2005-11-08 19:00:00,45544,0,6,399,27,0.427570,19,1,300,35426,10.0,0.090000,0,0.500402,-0.072833,316.0,18.0
11626,11630,Test,2005-11-08 19:05:00,45545,0,2,68,1,0.095030,19,1,52,35433,300.0,0.019231,0,0.427570,-0.332539,365.0,17.0
11627,11631,Test,2005-11-08 19:15:00,45547,0,1,68,0,0.000000,19,1,51,35433,52.0,0.000000,0,0.095030,-0.095030,414.0,17.0
11628,11632,Test,2005-11-08 19:20:00,45548,0,4,68,3,0.275593,19,1,54,35433,51.0,0.055556,0,0.000000,0.275593,467.0,20.0
11629,11633,Test,2005-11-08 19:25:00,45549,0,1,763,0,0.000000,19,1,3,35433,54.0,0.000000,0,0.275593,-0.275593,460.0,19.0
11630,11634,Test,2005-11-08 19:45:00,45553,0,1,606,0,0.000000,19,1,1,35433,3.0,0.000000,0,0.000000,0.000000,161.0,14.0

****************************************************************************************************
********************** Sequence Number Info ******************************************
****************************************************************************************************

Minimum Seq_Num: 4
Maximum Seq_Num: 14540
Total number of records: 14537

# <font color = red> Reset sequence & time_start_in for mapping file

In [8]:
import pandas as pd
from datetime import datetime

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
input_file = f"{data_dir}/20240714_225943_orig_input_w_seq_mapping_master.parquet"

# Generate timestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# Output file with timestamp
output_file = f"{data_dir}/{timestamp}_orig_input_w_seq_mapping_master_UPDATED.parquet"

# Load data
encoded_feature_input_file_df = pd.read_parquet(input_file)

# Reset the sequence numbers starting from 0
encoded_feature_input_file_df.reset_index(drop=True, inplace=True)
encoded_feature_input_file_df['Seq_Num'] = encoded_feature_input_file_df.index

# Reduce 4 from each value in the 'time_start_int' column
encoded_feature_input_file_df['time_start_int'] = encoded_feature_input_file_df['time_start_int'] - 4

# Save the updated DataFrame to a new parquet file
encoded_feature_input_file_df.to_parquet(output_file)

# Display the first few rows of the updated data
print("\n" + "*"*100)
print("********************** Updated Input Data with Features ******************************************")
print("*"*100 + "\n")
display(encoded_feature_input_file_df.iloc[:, :20].head())
print("Shape of Updated File with Features:", encoded_feature_input_file_df.shape)

# Display the last few rows of the updated data
print("\n" + "*"*100)
print("********************** Tail ******************************************")
print("*"*100 + "\n")
display(encoded_feature_input_file_df.iloc[:, :20].tail())

# Display records from sequence 11600 to 11630 with only the first 20 columns
print("\n" + "*"*100)
print("********************** Train Test Transition ******************************************")
print("*"*100 + "\n")
records_11600_to_11630 = encoded_feature_input_file_df.iloc[11600:11631, :20]
display(records_11600_to_11630)

# Print the minimum and maximum sequence numbers and the total number of records
min_seq_num = encoded_feature_input_file_df['Seq_Num'].min()
max_seq_num = encoded_feature_input_file_df['Seq_Num'].max()
total_records = len(encoded_feature_input_file_df)

print("\n" + "*"*100)
print("********************** Sequence Number Info ******************************************")
print("*"*100 + "\n")
print(f"Minimum Seq_Num: {min_seq_num}")
print(f"Maximum Seq_Num: {max_seq_num}")
print(f"Total number of records: {total_records}")

****************************************************************************************************
********************** Updated Input Data with Features ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
0,0,Train,2005-06-03 16:00:00,0,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0
1,1,Train,2005-06-03 16:05:00,1,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0
2,2,Train,2005-06-03 16:10:00,2,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0
3,3,Train,2005-06-03 16:15:00,3,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0
4,4,Train,2005-06-03 16:25:00,5,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0

Shape of Updated File with Features: (14537, 35453)

****************************************************************************************************
********************** Tail ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
14532,14532,Test,2006-01-04 07:35:00,61819,0,1,606,0,0.000000,7,2,1,35433,4.0,0.0,0,0.693147,-0.693147,53.0,18.0
14533,14533,Test,2006-01-04 07:40:00,61820,0,6,156,5,1.609438,7,2,10,35431,1.0,0.5,0,0.000000,1.609438,48.0,18.0
14534,14534,Test,2006-01-04 07:45:00,61821,0,2,193,1,0.693147,7,2,2,35433,10.0,0.5,0,1.609438,-0.916291,49.0,19.0
14535,14535,Test,2006-01-04 07:50:00,61822,0,3,156,2,1.039721,7,2,4,35433,2.0,0.5,0,0.693147,0.346574,21.0,19.0
14536,14536,Test,2006-01-04 08:00:00,61824,1,1,99,0,0.000000,8,2,8,35433,4.0,0.0,0,1.039721,-1.039721,25.0,18.0

****************************************************************************************************
********************** Train Test Transition ******************************************
****************************************************************************************************

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
11600,11600,Train,2005-11-08 13:50:00,45478,0,1,738,0,0.000000,13,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1043.0,12.0
11601,11601,Train,2005-11-08 14:00:00,45480,0,1,176,0,0.000000,14,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1036.0,12.0
11602,11602,Train,2005-11-08 14:10:00,45482,0,1,68,0,0.000000,14,1,13,35433,1.0,0.000000,0,0.000000,0.000000,1048.0,12.0
11603,11603,Train,2005-11-08 14:20:00,45484,0,1,68,0,0.000000,14,1,1,35433,13.0,0.000000,0,0.000000,0.000000,17.0,10.0
11604,11604,Train,2005-11-08 14:30:00,45486,0,3,108,2,0.483611,14,1,2910,35433,1.0,0.000687,0,0.000000,0.483611,2926.0,12.0
11605,11605,Train,2005-11-08 14:35:00,45487,0,2,108,1,0.029707,14,1,1714,35433,2910.0,0.000583,0,0.483611,-0.453904,4639.0,13.0
11606,11606,Train,2005-11-08 14:40:00,45488,0,2,108,1,0.348832,14,1,4608,35433,1714.0,0.000217,0,0.029707,0.319125,9246.0,14.0
11607,11607,Train,2005-11-08 15:05:00,45493,0,1,638,0,0.000000,15,1,16,35433,4608.0,0.000000,0,0.348832,-0.348832,9249.0,14.0
11608,11608,Train,2005-11-08 15:10:00,45494,0,2,68,1,0.693147,15,1,16,35433,16.0,0.062500,0,0.000000,0.693147,9264.0,15.0
11609,11609,Train,2005-11-08 15:15:00,45495,0,1,638,0,0.000000,15,1,8,35433,16.0,0.000000,0,0.693147,-0.693147,6362.0,13.0
11610,11610,Train,2005-11-08 15:25:00,45497,0,1,763,0,0.000000,15,1,3,35433,8.0,0.000000,0,0.000000,0.000000,4651.0,12.0
11611,11611,Test,2005-11-08 15:35:00,45499,0,1,638,0,0.000000,15,1,8,35433,3.0,0.000000,0,0.000000,0.000000,51.0,11.0
11612,11612,Test,2005-11-08 15:40:00,45500,0,1,68,0,0.000000,15,1,8,35433,8.0,0.000000,0,0.000000,0.000000,43.0,11.0
11613,11613,Test,2005-11-08 15:55:00,45503,0,1,68,0,0.000000,15,1,1,35433,8.0,0.000000,0,0.000000,0.000000,28.0,10.0
11614,11614,Test,2005-11-08 16:05:00,45505,0,1,68,0,0.000000,16,1,8,35433,1.0,0.000000,0,0.000000,0.000000,28.0,10.0
11615,11615,Test,2005-11-08 16:10:00,45506,0,1,68,0,0.000000,16,1,1,35433,8.0,0.000000,0,0.000000,0.000000,26.0,10.0
11616,11616,Test,2005-11-08 16:30:00,45510,0,4,399,9,1.251989,16,1,15,35433,1.0,0.600000,1,0.000000,1.251989,33.0,13.0
11617,11617,Test,2005-11-08 16:55:00,45515,0,1,176,0,0.000000,16,1,1,35433,15.0,0.000000,0,1.251989,-1.251989,26.0,13.0
11618,11618,Test,2005-11-08 17:25:00,45521,1,2,74,1,0.693147,17,1,1024,35433,1.0,0.000977,0,0.000000,0.693147,1049.0,14.0
11619,11619,Test,2005-11-08 17:30:00,45522,0,1,176,0,0.000000,17,1,1,35433,1024.0,0.000000,0,0.693147,-0.693147,1042.0,14.0
11620,11620,Test,2005-11-08 17:45:00,45525,0,1,68,0,0.000000,17,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1042.0,14.0
11621,11621,Test,2005-11-08 18:25:00,45533,0,3,95,2,1.098612,18,1,3,35433,1.0,0.666667,1,0.000000,1.098612,1030.0,13.0
11622,11622,Test,2005-11-08 18:35:00,45535,0,1,68,0,0.000000,18,1,2,35433,3.0,0.000000,0,1.098612,-1.098612,1031.0,13.0
11623,11623,Test,2005-11-08 18:40:00,45536,0,1,228,0,0.000000,18,1,1,35433,2.0,0.000000,0,0.000000,0.000000,8.0,12.0
11624,11624,Test,2005-11-08 18:50:00,45538,0,2,68,1,0.500402,18,1,10,35433,1.0,0.100000,0,0.000000,0.500402,17.0,13.0
11625,11625,Test,2005-11-08 19:00:00,45540,0,6,399,27,0.427570,19,1,300,35426,10.0,0.090000,0,0.500402,-0.072833,316.0,18.0
11626,11626,Test,2005-11-08 19:05:00,45541,0,2,68,1,0.095030,19,1,52,35433,300.0,0.019231,0,0.427570,-0.332539,365.0,17.0
11627,11627,Test,2005-11-08 19:15:00,45543,0,1,68,0,0.000000,19,1,51,35433,52.0,0.000000,0,0.095030,-0.095030,414.0,17.0
11628,11628,Test,2005-11-08 19:20:00,45544,0,4,68,3,0.275593,19,1,54,35433,51.0,0.055556,0,0.000000,0.275593,467.0,20.0
11629,11629,Test,2005-11-08 19:25:00,45545,0,1,763,0,0.000000,19,1,3,35433,54.0,0.000000,0,0.275593,-0.275593,460.0,19.0
11630,11630,Test,2005-11-08 19:45:00,45549,0,1,606,0,0.000000,19,1,1,35433,3.0,0.000000,0,0.000000,0.000000,161.0,14.0

****************************************************************************************************
********************** Sequence Number Info ******************************************
****************************************************************************************************

Minimum Seq_Num: 0
Maximum Seq_Num: 14536
Total number of records: 14537

___
# <font color = blue> Part 2. Run Inference for Multiple Records Manually (not API)

## Full - Summary

In [9]:
import os
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

# Parameters
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
model_folder_path = '/home/ubuntu/efs-w210-capstone-ebs/04B.Local_Model_Files/20240713_Non_Overlapping_Consl_180_FINAL'
trained_model_file = f"{model_folder_path}/20240712_Transformers_Non_Overlapping_run_133_of_180.pt"

# File prefix (should match the one used in Part 1)
file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with the actual prefix from Part 1

# Model parameters
input_length = 20
hidden_size = 64
dropout = 0.3
num_layers = 2

# Load the test data
X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")

# Drop the first column from X_test
X_test = X_test[:, :, 1:]

# Transformer Model Definition
class TransformerModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout=0.5):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_size, hidden_size)
        self.pos_encoder = nn.Embedding(input_length, hidden_size)
        self.transformer = nn.Transformer(hidden_size, nhead=4, num_encoder_layers=num_layers, num_decoder_layers=num_layers, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = self.embedding(x)
        positions = torch.arange(0, x.size(1), device=x.device).unsqueeze(0)
        x = x + self.pos_encoder(positions)
        x = self.transformer(x, x)
        x = self.fc(x[:, -1, :])
        return x

# Model Evaluation
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

input_size = X_test.shape[2]
model = TransformerModel(input_size, hidden_size, num_layers, 1, dropout)
model.load_state_dict(torch.load(trained_model_file))

model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_outputs = torch.sigmoid(test_outputs)
    test_outputs = test_outputs.cpu().numpy()

    test_preds = (test_outputs > 0.5).astype(int)

conf_matrix = confusion_matrix(y_test_tensor.cpu().numpy(), test_preds)
precision = precision_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
recall = recall_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
accuracy = accuracy_score(y_test_tensor.cpu().numpy(), test_preds)
f1 = f1_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
tn, fp, fn, tp = conf_matrix.ravel()

print(f"Evaluation Results: Precision={precision:.6f}, Recall={recall:.6f}, Accuracy={accuracy:.6f}, F1={f1:.6f}, TN={tn}, FP={fp}, FN={fn}, TP={tp}")

Evaluation Results: Precision=0.085106, Recall=0.888889, Accuracy=0.314961, F1=0.155340, TN=32, FP=86, FN=1, TP=8

## Full - Detail

In [10]:
import os
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

# Parameters
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
model_folder_path = '/home/ubuntu/efs-w210-capstone-ebs/04B.Local_Model_Files/20240713_Non_Overlapping_Consl_180_FINAL'
trained_model_file = f"{model_folder_path}/20240712_Transformers_Non_Overlapping_run_133_of_180.pt"

# File prefix (should match the one used in Part 1)
file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with the actual prefix from Part 1

# Model parameters
input_length = 20
hidden_size = 64
dropout = 0.3
num_layers = 2

# Load the test data
X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")

# Drop the first column from X_test
X_test = X_test[:, :, 1:]

# Transformer Model Definition
class TransformerModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout=0.5):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_size, hidden_size)
        self.pos_encoder = nn.Embedding(input_length, hidden_size)
        self.transformer = nn.Transformer(hidden_size, nhead=4, num_encoder_layers=num_layers, num_decoder_layers=num_layers, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = self.embedding(x)
        positions = torch.arange(0, x.size(1), device=x.device).unsqueeze(0)
        x = x + self.pos_encoder(positions)
        x = self.transformer(x, x)
        x = self.fc(x[:, -1, :])
        return x

# Model Evaluation
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

input_size = X_test.shape[2]
model = TransformerModel(input_size, hidden_size, num_layers, 1, dropout)
model.load_state_dict(torch.load(trained_model_file))

model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_outputs = torch.sigmoid(test_outputs)
    test_outputs = test_outputs.cpu().numpy()

    test_preds = (test_outputs > 0.5).astype(int)

# Print each test set's predicted vs actual value
print("Test Set Predictions vs Actual Values:")
for i in range(len(test_preds)):
    print(f"Test {i+1}: Predicted={test_preds[i][0]}, Actual={y_test_tensor[i].item()}")

# Calculate and print metrics
conf_matrix = confusion_matrix(y_test_tensor.cpu().numpy(), test_preds)
precision = precision_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
recall = recall_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
accuracy = accuracy_score(y_test_tensor.cpu().numpy(), test_preds)
f1 = f1_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
tn, fp, fn, tp = conf_matrix.ravel()

print("\nEvaluation Results:")
print(f"Precision={precision:.6f}, Recall={recall:.6f}, Accuracy={accuracy:.6f}, F1={f1:.6f}, TN={tn}, FP={fp}, FN={fn}, TP={tp}")

Test Set Predictions vs Actual Values:
Test 1: Predicted=0, Actual=0.0
Test 2: Predicted=0, Actual=0.0
Test 3: Predicted=1, Actual=0.0
Test 4: Predicted=1, Actual=0.0
Test 5: Predicted=1, Actual=0.0
Test 6: Predicted=1, Actual=0.0
Test 7: Predicted=0, Actual=0.0
Test 8: Predicted=0, Actual=0.0
Test 9: Predicted=0, Actual=0.0
Test 10: Predicted=0, Actual=0.0
Test 11: Predicted=1, Actual=0.0
Test 12: Predicted=1, Actual=0.0
Test 13: Predicted=1, Actual=0.0
Test 14: Predicted=0, Actual=0.0
Test 15: Predicted=1, Actual=0.0
Test 16: Predicted=1, Actual=0.0
Test 17: Predicted=0, Actual=0.0
Test 18: Predicted=1, Actual=0.0
Test 19: Predicted=1, Actual=1.0
Test 20: Predicted=1, Actual=1.0
Test 21: Predicted=0, Actual=0.0
Test 22: Predicted=1, Actual=0.0
Test 23: Predicted=1, Actual=0.0
Test 24: Predicted=1, Actual=0.0
Test 25: Predicted=1, Actual=0.0
Test 26: Predicted=1, Actual=1.0
Test 27: Predicted=0, Actual=0.0
Test 28: Predicted=1, Actual=0.0
Test 29: Predicted=1, Actual=0.0
Test 30: Predicted=1, Actual=0.0
Test 31: Predicted=0, Actual=0.0
Test 32: Predicted=1, Actual=0.0
Test 33: Predicted=1, Actual=0.0
Test 34: Predicted=1, Actual=0.0
Test 35: Predicted=1, Actual=0.0
Test 36: Predicted=0, Actual=0.0
Test 37: Predicted=1, Actual=1.0
Test 38: Predicted=1, Actual=0.0
Test 39: Predicted=1, Actual=1.0
Test 40: Predicted=1, Actual=0.0
Test 41: Predicted=1, Actual=0.0
Test 42: Predicted=0, Actual=0.0
Test 43: Predicted=1, Actual=0.0
Test 44: Predicted=1, Actual=0.0
Test 45: Predicted=1, Actual=0.0
Test 46: Predicted=1, Actual=0.0
Test 47: Predicted=0, Actual=0.0
Test 48: Predicted=0, Actual=0.0
Test 49: Predicted=1, Actual=0.0
Test 50: Predicted=1, Actual=0.0
Test 51: Predicted=1, Actual=1.0
Test 52: Predicted=0, Actual=0.0
Test 53: Predicted=1, Actual=0.0
Test 54: Predicted=1, Actual=0.0
Test 55: Predicted=1, Actual=0.0
Test 56: Predicted=1, Actual=0.0
Test 57: Predicted=1, Actual=0.0
Test 58: Predicted=1, Actual=0.0
Test 59: Predicted=1, Actual=0.0
Test 60: Predicted=1, Actual=0.0
Test 61: Predicted=1, Actual=0.0
Test 62: Predicted=0, Actual=0.0
Test 63: Predicted=1, Actual=0.0
Test 64: Predicted=1, Actual=0.0
Test 65: Predicted=1, Actual=0.0
Test 66: Predicted=1, Actual=0.0
Test 67: Predicted=1, Actual=1.0
Test 68: Predicted=1, Actual=0.0
Test 69: Predicted=1, Actual=0.0
Test 70: Predicted=1, Actual=0.0
Test 71: Predicted=1, Actual=0.0
Test 72: Predicted=0, Actual=0.0
Test 73: Predicted=1, Actual=0.0
Test 74: Predicted=0, Actual=0.0
Test 75: Predicted=1, Actual=0.0
Test 76: Predicted=0, Actual=0.0
Test 77: Predicted=1, Actual=0.0
Test 78: Predicted=0, Actual=0.0
Test 79: Predicted=0, Actual=0.0
Test 80: Predicted=1, Actual=0.0
Test 81: Predicted=1, Actual=0.0
Test 82: Predicted=0, Actual=0.0
Test 83: Predicted=0, Actual=0.0
Test 84: Predicted=1, Actual=1.0
Test 85: Predicted=1, Actual=0.0
Test 86: Predicted=0, Actual=0.0
Test 87: Predicted=1, Actual=0.0
Test 88: Predicted=1, Actual=0.0
Test 89: Predicted=1, Actual=0.0
Test 90: Predicted=1, Actual=0.0
Test 91: Predicted=0, Actual=0.0
Test 92: Predicted=1, Actual=0.0
Test 93: Predicted=0, Actual=1.0
Test 94: Predicted=0, Actual=0.0
Test 95: Predicted=1, Actual=0.0
Test 96: Predicted=1, Actual=0.0
Test 97: Predicted=1, Actual=0.0
Test 98: Predicted=0, Actual=0.0
Test 99: Predicted=1, Actual=0.0
Test 100: Predicted=1, Actual=0.0
Test 101: Predicted=0, Actual=0.0
Test 102: Predicted=1, Actual=0.0
Test 103: Predicted=1, Actual=0.0
Test 104: Predicted=1, Actual=0.0
Test 105: Predicted=1, Actual=0.0
Test 106: Predicted=0, Actual=0.0
Test 107: Predicted=1, Actual=0.0
Test 108: Predicted=1, Actual=0.0
Test 109: Predicted=1, Actual=0.0
Test 110: Predicted=0, Actual=0.0
Test 111: Predicted=1, Actual=0.0
Test 112: Predicted=1, Actual=0.0
Test 113: Predicted=1, Actual=0.0
Test 114: Predicted=1, Actual=0.0
Test 115: Predicted=1, Actual=0.0
Test 116: Predicted=1, Actual=0.0
Test 117: Predicted=1, Actual=0.0
Test 118: Predicted=1, Actual=0.0
Test 119: Predicted=1, Actual=0.0
Test 120: Predicted=1, Actual=0.0
Test 121: Predicted=1, Actual=0.0
Test 122: Predicted=0, Actual=0.0
Test 123: Predicted=1, Actual=0.0
Test 124: Predicted=1, Actual=0.0
Test 125: Predicted=1, Actual=0.0
Test 126: Predicted=1, Actual=0.0
Test 127: Predicted=1, Actual=0.0

Evaluation Results:
Precision=0.085106, Recall=0.888889, Accuracy=0.314961, F1=0.155340, TN=32, FP=86, FN=1, TP=8

## Inference Tracking File - Solo

In [11]:
import os
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
from datetime import datetime

# Parameters
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
model_folder_path = '/home/ubuntu/efs-w210-capstone-ebs/04B.Local_Model_Files/20240713_Non_Overlapping_Consl_180_FINAL'
trained_model_file = f"{model_folder_path}/20240712_Transformers_Non_Overlapping_run_133_of_180.pt"

# File prefix (should match the one used in Part 1)
file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with the actual prefix from Part 1

# Model parameters
input_length = 20
hidden_size = 64
dropout = 0.3
num_layers = 2

# Load the test data
X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")
indices_test_path = f"{data_dir}/20240714_221127_non_overlap_full_test_indices_test.npy"
indices_test = np.load(indices_test_path)

# Drop the first column from X_test
X_test = X_test[:, :, 1:]

# Transformer Model Definition
class TransformerModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout=0.5):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_size, hidden_size)
        self.pos_encoder = nn.Embedding(input_length, hidden_size)
        self.transformer = nn.Transformer(hidden_size, nhead=4, num_encoder_layers=num_layers, num_decoder_layers=num_layers, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = self.embedding(x)
        positions = torch.arange(0, x.size(1), device=x.device).unsqueeze(0)
        x = x + self.pos_encoder(positions)
        x = self.transformer(x, x)
        x = self.fc(x[:, -1, :])
        return x

# Model Evaluation
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

input_size = X_test.shape[2]
model = TransformerModel(input_size, hidden_size, num_layers, 1, dropout)
model.load_state_dict(torch.load(trained_model_file))

model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_outputs = torch.sigmoid(test_outputs)
    test_outputs = test_outputs.cpu().numpy()

    test_preds = (test_outputs > 0.5).astype(int)

# Create DataFrame for tracking
results_df = pd.DataFrame({
    "Predicted": test_preds.flatten(),
    "Actual": y_test,
    "Total_Seq_Start": indices_test[:, 0],
    "Total_Seq_End": indices_test[:, 1],
    "Source_Seq_Start": indices_test[:, 0],
    "Source_Seq_End": indices_test[:, 0] + input_length - 1,
    "Gap_Seq_Start": indices_test[:, 0] + input_length,
    "Gap_Seq_End": indices_test[:, 0] + input_length + 1,
    "Prediction_Seq_Start": indices_test[:, 1] - 1,
    "Prediction_Seq_End": indices_test[:, 1]
})

# Save DataFrame to CSV
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_file = f"{data_dir}/{timestamp}_non_overlapping_inference_tracking.csv"
results_df.to_csv(output_file, index=False)

print(f"Tracking file saved to {output_file}")

# Print each test set's predicted vs actual value
print("Test Set Predictions vs Actual Values:")
display(results_df[["Total_Seq_Start", "Total_Seq_End", "Source_Seq_Start", "Source_Seq_End", "Gap_Seq_Start", "Gap_Seq_End", "Prediction_Seq_Start", "Prediction_Seq_End", "Predicted", "Actual"]])

# Calculate and print metrics
conf_matrix = confusion_matrix(y_test_tensor.cpu().numpy(), test_preds)
precision = precision_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
recall = recall_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
accuracy = accuracy_score(y_test_tensor.cpu().numpy(), test_preds)
f1 = f1_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
tn, fp, fn, tp = conf_matrix.ravel()

print("\nEvaluation Results:")
print(f"Precision={precision:.6f}, Recall={recall:.6f}, Accuracy={accuracy:.6f}, F1={f1:.6f}, TN={tn}, FP={fp}, FN={fn}, TP={tp}")

Tracking file saved to /home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files/20240715_012515_non_overlapping_inference_tracking.csv
Test Set Predictions vs Actual Values:

,Total_Seq_Start,Total_Seq_End,Source_Seq_Start,Source_Seq_End,Gap_Seq_Start,Gap_Seq_End,Prediction_Seq_Start,Prediction_Seq_End,Predicted,Actual
0,11615,11638,11615,11634,11635,11636,11637,11638,0,0.0
1,11638,11661,11638,11657,11658,11659,11660,11661,0,0.0
2,11661,11684,11661,11680,11681,11682,11683,11684,1,0.0
3,11684,11707,11684,11703,11704,11705,11706,11707,1,0.0
4,11707,11730,11707,11726,11727,11728,11729,11730,1,0.0
5,11730,11753,11730,11749,11750,11751,11752,11753,1,0.0
6,11753,11776,11753,11772,11773,11774,11775,11776,0,0.0
7,11776,11799,11776,11795,11796,11797,11798,11799,0,0.0
8,11799,11822,11799,11818,11819,11820,11821,11822,0,0.0
9,11822,11845,11822,11841,11842,11843,11844,11845,0,0.0
10,11845,11868,11845,11864,11865,11866,11867,11868,1,0.0
11,11868,11891,11868,11887,11888,11889,11890,11891,1,0.0
12,11891,11914,11891,11910,11911,11912,11913,11914,1,0.0
13,11914,11937,11914,11933,11934,11935,11936,11937,0,0.0
14,11937,11960,11937,11956,11957,11958,11959,11960,1,0.0
15,11960,11983,11960,11979,11980,11981,11982,11983,1,0.0
16,11983,12006,11983,12002,12003,12004,12005,12006,0,0.0
17,12006,12029,12006,12025,12026,12027,12028,12029,1,0.0
18,12029,12052,12029,12048,12049,12050,12051,12052,1,1.0
19,12052,12075,12052,12071,12072,12073,12074,12075,1,1.0
20,12075,12098,12075,12094,12095,12096,12097,12098,0,0.0
21,12098,12121,12098,12117,12118,12119,12120,12121,1,0.0
22,12121,12144,12121,12140,12141,12142,12143,12144,1,0.0
23,12144,12167,12144,12163,12164,12165,12166,12167,1,0.0
24,12167,12190,12167,12186,12187,12188,12189,12190,1,0.0
25,12190,12213,12190,12209,12210,12211,12212,12213,1,1.0
26,12213,12236,12213,12232,12233,12234,12235,12236,0,0.0
27,12236,12259,12236,12255,12256,12257,12258,12259,1,0.0
28,12259,12282,12259,12278,12279,12280,12281,12282,1,0.0
29,12282,12305,12282,12301,12302,12303,12304,12305,1,0.0
30,12305,12328,12305,12324,12325,12326,12327,12328,0,0.0
31,12328,12351,12328,12347,12348,12349,12350,12351,1,0.0
32,12351,12374,12351,12370,12371,12372,12373,12374,1,0.0
33,12374,12397,12374,12393,12394,12395,12396,12397,1,0.0
34,12397,12420,12397,12416,12417,12418,12419,12420,1,0.0
35,12420,12443,12420,12439,12440,12441,12442,12443,0,0.0
36,12443,12466,12443,12462,12463,12464,12465,12466,1,1.0
37,12466,12489,12466,12485,12486,12487,12488,12489,1,0.0
38,12489,12512,12489,12508,12509,12510,12511,12512,1,1.0
39,12512,12535,12512,12531,12532,12533,12534,12535,1,0.0
40,12535,12558,12535,12554,12555,12556,12557,12558,1,0.0
41,12558,12581,12558,12577,12578,12579,12580,12581,0,0.0
42,12581,12604,12581,12600,12601,12602,12603,12604,1,0.0
43,12604,12627,12604,12623,12624,12625,12626,12627,1,0.0
44,12627,12650,12627,12646,12647,12648,12649,12650,1,0.0
45,12650,12673,12650,12669,12670,12671,12672,12673,1,0.0
46,12673,12696,12673,12692,12693,12694,12695,12696,0,0.0
47,12696,12719,12696,12715,12716,12717,12718,12719,0,0.0
48,12719,12742,12719,12738,12739,12740,12741,12742,1,0.0
49,12742,12765,12742,12761,12762,12763,12764,12765,1,0.0
50,12765,12788,12765,12784,12785,12786,12787,12788,1,1.0
51,12788,12811,12788,12807,12808,12809,12810,12811,0,0.0
52,12811,12834,12811,12830,12831,12832,12833,12834,1,0.0
53,12834,12857,12834,12853,12854,12855,12856,12857,1,0.0
54,12857,12880,12857,12876,12877,12878,12879,12880,1,0.0
55,12880,12903,12880,12899,12900,12901,12902,12903,1,0.0
56,12903,12926,12903,12922,12923,12924,12925,12926,1,0.0
57,12926,12949,12926,12945,12946,12947,12948,12949,1,0.0
58,12949,12972,12949,12968,12969,12970,12971,12972,1,0.0
59,12972,12995,12972,12991,12992,12993,12994,12995,1,0.0
60,12995,13018,12995,13014,13015,13016,13017,13018,1,0.0
61,13018,13041,13018,13037,13038,13039,13040,13041,0,0.0
62,13041,13064,13041,13060,13061,13062,13063,13064,1,0.0
63,13064,13087,13064,13083,13084,13085,13086,13087,1,0.0
64,13087,13110,13087,13106,13107,13108,13109,13110,1,0.0
65,13110,13133,13110,13129,13130,13131,13132,13133,1,0.0
66,13133,13156,13133,13152,13153,13154,13155,13156,1,1.0
67,13156,13179,13156,13175,13176,13177,13178,13179,1,0.0
68,13179,13202,13179,13198,13199,13200,13201,13202,1,0.0
69,13202,13225,13202,13221,13222,13223,13224,13225,1,0.0
70,13225,13248,13225,13244,13245,13246,13247,13248,1,0.0
71,13248,13271,13248,13267,13268,13269,13270,13271,0,0.0
72,13271,13294,13271,13290,13291,13292,13293,13294,1,0.0
73,13294,13317,13294,13313,13314,13315,13316,13317,0,0.0
74,13317,13340,13317,13336,13337,13338,13339,13340,1,0.0
75,13340,13363,13340,13359,13360,13361,13362,13363,0,0.0
76,13363,13386,13363,13382,13383,13384,13385,13386,1,0.0
77,13386,13409,13386,13405,13406,13407,13408,13409,0,0.0
78,13409,13432,13409,13428,13429,13430,13431,13432,0,0.0
79,13432,13455,13432,13451,13452,13453,13454,13455,1,0.0
80,13455,13478,13455,13474,13475,13476,13477,13478,1,0.0
81,13478,13501,13478,13497,13498,13499,13500,13501,0,0.0
82,13501,13524,13501,13520,13521,13522,13523,13524,0,0.0
83,13524,13547,13524,13543,13544,13545,13546,13547,1,1.0
84,13547,13570,13547,13566,13567,13568,13569,13570,1,0.0
85,13570,13593,13570,13589,13590,13591,13592,13593,0,0.0
86,13593,13616,13593,13612,13613,13614,13615,13616,1,0.0
87,13616,13639,13616,13635,13636,13637,13638,13639,1,0.0
88,13639,13662,13639,13658,13659,13660,13661,13662,1,0.0
89,13662,13685,13662,13681,13682,13683,13684,13685,1,0.0
90,13685,13708,13685,13704,13705,13706,13707,13708,0,0.0
91,13708,13731,13708,13727,13728,13729,13730,13731,1,0.0
92,13731,13754,13731,13750,13751,13752,13753,13754,0,1.0
93,13754,13777,13754,13773,13774,13775,13776,13777,0,0.0
94,13777,13800,13777,13796,13797,13798,13799,13800,1,0.0
95,13800,13823,13800,13819,13820,13821,13822,13823,1,0.0
96,13823,13846,13823,13842,13843,13844,13845,13846,1,0.0
97,13846,13869,13846,13865,13866,13867,13868,13869,0,0.0
98,13869,13892,13869,13888,13889,13890,13891,13892,1,0.0
99,13892,13915,13892,13911,13912,13913,13914,13915,1,0.0
100,13915,13938,13915,13934,13935,13936,13937,13938,0,0.0
101,13938,13961,13938,13957,13958,13959,13960,13961,1,0.0
102,13961,13984,13961,13980,13981,13982,13983,13984,1,0.0
103,13984,14007,13984,14003,14004,14005,14006,14007,1,0.0
104,14007,14030,14007,14026,14027,14028,14029,14030,1,0.0
105,14030,14053,14030,14049,14050,14051,14052,14053,0,0.0
106,14053,14076,14053,14072,14073,14074,14075,14076,1,0.0
107,14076,14099,14076,14095,14096,14097,14098,14099,1,0.0
108,14099,14122,14099,14118,14119,14120,14121,14122,1,0.0
109,14122,14145,14122,14141,14142,14143,14144,14145,0,0.0
110,14145,14168,14145,14164,14165,14166,14167,14168,1,0.0
111,14168,14191,14168,14187,14188,14189,14190,14191,1,0.0
112,14191,14214,14191,14210,14211,14212,14213,14214,1,0.0
113,14214,14237,14214,14233,14234,14235,14236,14237,1,0.0
114,14237,14260,14237,14256,14257,14258,14259,14260,1,0.0
115,14260,14283,14260,14279,14280,14281,14282,14283,1,0.0
116,14283,14306,14283,14302,14303,14304,14305,14306,1,0.0
117,14306,14329,14306,14325,14326,14327,14328,14329,1,0.0
118,14329,14352,14329,14348,14349,14350,14351,14352,1,0.0
119,14352,14375,14352,14371,14372,14373,14374,14375,1,0.0
120,14375,14398,14375,14394,14395,14396,14397,14398,1,0.0
121,14398,14421,14398,14417,14418,14419,14420,14421,0,0.0
122,14421,14444,14421,14440,14441,14442,14443,14444,1,0.0
123,14444,14467,14444,14463,14464,14465,14466,14467,1,0.0
124,14467,14490,14467,14486,14487,14488,14489,14490,1,0.0
125,14490,14513,14490,14509,14510,14511,14512,14513,1,0.0
126,14513,14536,14513,14532,14533,14534,14535,14536,1,0.0

Evaluation Results:
Precision=0.085106, Recall=0.888889, Accuracy=0.314961, F1=0.155340, TN=32, FP=86, FN=1, TP=8

___
## Inference Tracking File - Mapped to Source Parquet

In [12]:
import numpy as np

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
indices_test_path = f"{data_dir}/20240714_221127_non_overlap_full_test_indices_test.npy"

# Load the .npy file
indices_test = np.load(indices_test_path)

# Display the contents
print(indices_test)

[[11615 11638]
 [11638 11661]
 [11661 11684]
 [11684 11707]
 [11707 11730]
 [11730 11753]
 [11753 11776]
 [11776 11799]
 [11799 11822]
 [11822 11845]
 [11845 11868]
 [11868 11891]
 [11891 11914]
 [11914 11937]
 [11937 11960]
 [11960 11983]
 [11983 12006]
 [12006 12029]
 [12029 12052]
 [12052 12075]
 [12075 12098]
 [12098 12121]
 [12121 12144]
 [12144 12167]
 [12167 12190]
 [12190 12213]
 [12213 12236]
 [12236 12259]
 [12259 12282]
 [12282 12305]
 [12305 12328]
 [12328 12351]
 [12351 12374]
 [12374 12397]
 [12397 12420]
 [12420 12443]
 [12443 12466]
 [12466 12489]
 [12489 12512]
 [12512 12535]
 [12535 12558]
 [12558 12581]
 [12581 12604]
 [12604 12627]
 [12627 12650]
 [12650 12673]
 [12673 12696]
 [12696 12719]
 [12719 12742]
 [12742 12765]
 [12765 12788]
 [12788 12811]
 [12811 12834]
 [12834 12857]
 [12857 12880]
 [12880 12903]
 [12903 12926]
 [12926 12949]
 [12949 12972]
 [12972 12995]
 [12995 13018]
 [13018 13041]
 [13041 13064]
 [13064 13087]
 [13087 13110]
 [13110 13133]
 [13133 13156]
 [13156 13179]
 [13179 13202]
 [13202 13225]
 [13225 13248]
 [13248 13271]
 [13271 13294]
 [13294 13317]
 [13317 13340]
 [13340 13363]
 [13363 13386]
 [13386 13409]
 [13409 13432]
 [13432 13455]
 [13455 13478]
 [13478 13501]
 [13501 13524]
 [13524 13547]
 [13547 13570]
 [13570 13593]
 [13593 13616]
 [13616 13639]
 [13639 13662]
 [13662 13685]
 [13685 13708]
 [13708 13731]
 [13731 13754]
 [13754 13777]
 [13777 13800]
 [13800 13823]
 [13823 13846]
 [13846 13869]
 [13869 13892]
 [13892 13915]
 [13915 13938]
 [13938 13961]
 [13961 13984]
 [13984 14007]
 [14007 14030]
 [14030 14053]
 [14053 14076]
 [14076 14099]
 [14099 14122]
 [14122 14145]
 [14145 14168]
 [14168 14191]
 [14191 14214]
 [14214 14237]
 [14237 14260]
 [14260 14283]
 [14283 14306]
 [14306 14329]
 [14329 14352]
 [14352 14375]
 [14375 14398]
 [14398 14421]
 [14421 14444]
 [14444 14467]
 [14467 14490]
 [14490 14513]
 [14513 14536]]

In [ ]:
import os
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
from datetime import datetime

# Parameters
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
model_folder_path = '/home/ubuntu/efs-w210-capstone-ebs/04B.Local_Model_Files/20240713_Non_Overlapping_Consl_180_FINAL'
trained_model_file = f"{model_folder_path}/20240712_Transformers_Non_Overlapping_run_133_of_180.pt"

# File prefix (should match the one used in Part 1)
file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with the actual prefix from Part 1

# Model parameters
input_length = 20
hidden_size = 64
dropout = 0.3
num_layers = 2

# Load the test data
X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")
indices_test_path = f"{data_dir}/20240714_221127_non_overlap_full_test_indices_test.npy"
indices_test = np.load(indices_test_path)

# Load the original parquet file and select the first 20 columns
input_file = f"{data_dir}/20240714_225943_orig_input_w_seq_mapping_master.parquet"
original_df = pd.read_parquet(input_file).iloc[:, :20]

# Drop the first column from X_test
X_test = X_test[:, :, 1:]

# Transformer Model Definition
class TransformerModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout=0.5):
        super(TransformerModel, self).__init__()
        self.embedding = nn.Linear(input_size, hidden_size)
        self.pos_encoder = nn.Embedding(input_length, hidden_size)
        self.transformer = nn.Transformer(hidden_size, nhead=4, num_encoder_layers=num_layers, num_decoder_layers=num_layers, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = self.embedding(x)
        positions = torch.arange(0, x.size(1), device=x.device).unsqueeze(0)
        x = x + self.pos_encoder(positions)
        x = self.transformer(x, x)
        x = self.fc(x[:, -1, :])
        return x

# Model Evaluation
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

input_size = X_test.shape[2]
model = TransformerModel(input_size, hidden_size, num_layers, 1, dropout)
model.load_state_dict(torch.load(trained_model_file))

model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_outputs = torch.sigmoid(test_outputs)
    test_outputs = test_outputs.cpu().numpy()

    test_preds = (test_outputs > 0.5).astype(int)

# Create DataFrame for tracking
results_df = pd.DataFrame({
    "Predicted": test_preds.flatten(),
    "Actual": y_test,
    "Total_Seq_Start": indices_test[:, 0],
    "Total_Seq_End": indices_test[:, 1],
    "Source_Seq_Start": indices_test[:, 0],
    "Source_Seq_End": indices_test[:, 0] + input_length - 1,
    "Gap_Seq_Start": indices_test[:, 0] + input_length,
    "Gap_Seq_End": indices_test[:, 0] + input_length + 1,
    "Prediction_Seq_Start": indices_test[:, 1] - 1,
    "Prediction_Seq_End": indices_test[:, 1]
})

# Map and pull the 20 matching columns from the original parquet file
mapped_columns = []
for index, row in results_df.iterrows():
    seq_start = int(row['Total_Seq_Start'])
    seq_end = int(row['Total_Seq_End'])
    orig_data = original_df.loc[seq_start:seq_end].reset_index(drop=True)
    mapped_columns.append(orig_data)

# Concatenate all the mapped columns
mapped_df = pd.concat(mapped_columns, ignore_index=True)

# Combine the results DataFrame with the mapped original data
final_df = pd.concat([results_df, mapped_df], axis=1)

# Save DataFrame to CSV
output_file = f"{data_dir}/non_overlapping_inference_map_to_orig.csv"
final_df.to_csv(output_file, index=False)

print(f"New mapping file saved to {output_file}")

# Display the first few rows of the new DataFrame
display(final_df.head())

# Calculate and print metrics
conf_matrix = confusion_matrix(y_test_tensor.cpu().numpy(), test_preds)
precision = precision_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
recall = recall_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
accuracy = accuracy_score(y_test_tensor.cpu().numpy(), test_preds)
f1 = f1_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
tn, fp, fn, tp = conf_matrix.ravel()

print("\nEvaluation Results:")
print(f"Precision={precision:.6f}, Recall={recall:.6f}, Accuracy={accuracy:.6f}, F1={f1:.6f}, TN={tn}, FP={fp}, FN={fn}, TP={tp}")

## Map and Pull invidual event columns (not single one)

In [ ]:
# import os
# import torch
# import torch.nn as nn
# import numpy as np
# import pandas as pd
# from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
# from datetime import datetime

# # Parameters
# data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
# model_folder_path = '/home/ubuntu/efs-w210-capstone-ebs/04B.Local_Model_Files/20240713_Non_Overlapping_Consl_180_FINAL'
# trained_model_file = f"{model_folder_path}/20240712_Transformers_Non_Overlapping_run_133_of_180.pt"

# # File prefix (should match the one used in Part 1)
# file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with the actual prefix from Part 1

# # Model parameters
# input_length = 20
# hidden_size = 64
# dropout = 0.3
# num_layers = 2

# # Load the test data
# X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
# y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")
# indices_test_path = f"{data_dir}/20240714_221127_non_overlap_full_test_indices_test.npy"
# indices_test = np.load(indices_test_path)

# # Load the original parquet file and select the first 20 columns
# input_file = f"{data_dir}/20240714_225943_orig_input_w_seq_mapping_master.parquet"
# original_df = pd.read_parquet(input_file).iloc[:, :20]

# # Drop the first column from X_test
# X_test = X_test[:, :, 1:]

# # Transformer Model Definition
# class TransformerModel(nn.Module):
#     def __init__(self, input_size, hidden_size, num_layers, output_size, dropout=0.5):
#         super(TransformerModel, self).__init__()
#         self.embedding = nn.Linear(input_size, hidden_size)
#         self.pos_encoder = nn.Embedding(input_length, hidden_size)
#         self.transformer = nn.Transformer(hidden_size, nhead=4, num_encoder_layers=num_layers, num_decoder_layers=num_layers, dropout=dropout)
#         self.fc = nn.Linear(hidden_size, output_size)
    
#     def forward(self, x):
#         x = self.embedding(x)
#         positions = torch.arange(0, x.size(1), device=x.device).unsqueeze(0)
#         x = x + self.pos_encoder(positions)
#         x = self.transformer(x, x)
#         x = self.fc(x[:, -1, :])
#         return x

# # Model Evaluation
# X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
# y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# input_size = X_test.shape[2]
# model = TransformerModel(input_size, hidden_size, num_layers, 1, dropout)
# model.load_state_dict(torch.load(trained_model_file))

# model.eval()
# with torch.no_grad():
#     test_outputs = model(X_test_tensor)
#     test_outputs = torch.sigmoid(test_outputs)
#     test_outputs = test_outputs.cpu().numpy()

#     test_preds = (test_outputs > 0.5).astype(int)

# # Create DataFrame for tracking
# results_df = pd.DataFrame({
#     "Predicted": test_preds.flatten(),
#     "Actual": y_test,
#     "Total_Seq_Start": indices_test[:, 0],
#     "Total_Seq_End": indices_test[:, 1],
#     "Source_Seq_Start": indices_test[:, 0],
#     "Source_Seq_End": indices_test[:, 0] + input_length - 1,
#     "Gap_Seq_Start": indices_test[:, 0] + input_length,
#     "Gap_Seq_End": indices_test[:, 0] + input_length + 1,
#     "Prediction_Seq_Start": indices_test[:, 1] - 1,
#     "Prediction_Seq_End": indices_test[:, 1]
# })

# # Initialize list to hold new rows with original data
# new_rows = []

# # Map and pull the 20 matching columns from the original parquet file for each source period
# for _, row in results_df.iterrows():
#     seq_start = int(row['Source_Seq_Start'])
#     seq_end = int(row['Source_Seq_End'])
    
#     # Extract the corresponding rows from the original DataFrame
#     orig_data_range = original_df.loc[seq_start:seq_end].copy()
    
#     # Repeat the tracking information for each row in the range
#     tracking_info = row.to_frame().T
#     tracking_info_repeated = pd.concat([tracking_info] * len(orig_data_range), ignore_index=True)
    
#     # Add a column to represent the sequence number from the original DataFrame
#     tracking_info_repeated['Seq_Num'] = orig_data_range.index
    
#     # Concatenate tracking information and original data horizontally
#     combined_data = pd.concat([tracking_info_repeated.reset_index(drop=True), orig_data_range.reset_index(drop=True)], axis=1)
    
#     new_rows.append(combined_data)

# # Concatenate all the new rows into a final DataFrame
# final_df = pd.concat(new_rows, ignore_index=True)

# # Save the final DataFrame to a CSV file with a timestamp
# timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
# output_file = f"{data_dir}/{timestamp}_non_overlapping_inference_map_to_orig.csv"
# final_df.to_csv(output_file, index=False)

# print(f"New mapping file saved to {output_file}")

# # Display the first few rows of the new DataFrame
# display(final_df.head())

# # Calculate and print metrics
# conf_matrix = confusion_matrix(y_test_tensor.cpu().numpy(), test_preds)
# precision = precision_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
# recall = recall_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
# accuracy = accuracy_score(y_test_tensor.cpu().numpy(), test_preds)
# f1 = f1_score(y_test_tensor.cpu().numpy(), test_preds, zero_division=0)
# tn, fp, fn, tp = conf_matrix.ravel()

# print("\nEvaluation Results:")
# print(f"Precision={precision:.6f}, Recall={recall:.6f}, Accuracy={accuracy:.6f}, F1={f1:.6f}, TN={tn}, FP={fp}, FN={fn}, TP={tp}")