# <font color = lightcoral>Sequence Matching Finalize
>

## <font color = grey> Admin

In [4]:
import pandas as pd
import os
import gzip
import time
import warnings
import os
import shutil
from datetime import datetime
import time
# Set display option to show the full length of the column
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

# Determine the base directory based on the effective user ID
if os.geteuid() == 0:  # root user
    base_dir = '/root'
else:
    base_dir = '/home/sagemaker-user'

# Set the environment variable
os.environ['BASE_DIR'] = base_dir

# Verify the base directory
print(f"Base directory set to: {base_dir}")

import warnings
warnings.simplefilter("ignore")

Base directory set to: /home/sagemaker-user

---

# <font color = lightsteelblue> 4 Key Files

In [5]:
import pandas as pd
import time

data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04A.Local_Data_Files'

################################## Part 1: Parsed Raw File ###################################

print("\n" + "*"*100)
print("********************** Part1 1: Parsed Raw File ******************************************")
print("*"*100 + "\n")

parsed_file =  f"{data_dir}/BGL.log_structured.csv"
parsed_file_df = pd.read_csv(parsed_file)
display(parsed_file_df.head())
print("Shape of Parsed Raw File:", parsed_file_df.shape)

######################### Part 2: Encoded File with Feature for Model Training  ######################

print("\n" + "*"*100)
print("********************** Part 2:  Input Data with Features ******************************************")
print("*"*100 + "\n")

encoded_feature_input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
encoded_feature_input_file_df = pd.read_parquet(encoded_feature_input_file)
display(encoded_feature_input_file_df.iloc[:, :20].head())
print("Shape of Encoded File with Features:", encoded_feature_input_file_df.shape)

# ######################### Part 3: Event_ID to Template Mapping  #######################################

print("\n" + "*"*100)
print("********************** Part 3: Event_ID to Template Mapping ******************************************")
print("*"*100 + "\n")

eventid_template_file = f"{data_dir}/20240711_Template_to_EventID_Mapping_v1.00.csv"
eventid_template_df = pd.read_csv(eventid_template_file)
display(eventid_template_df.head())
print("Shape of Event_ID to Template Mapping:", eventid_template_df.shape)

# ######################### Part 4: Event_ID to Encoding Mapping  #######################################

print("\n" + "*"*100)
print("********************** Part 4:  Event_ID to Encoding Mapping ******************************************")
print("*"*100 + "\n")

eventid_encoding_file = f"{data_dir}/20240711_EventID_to_EncodedInteger_Mapping_v1.00.csv"
eventid_encoding_df = pd.read_csv(eventid_encoding_file)
display(eventid_encoding_df.head())
print("Shape of Event_ID to Encoding Mapping:", eventid_encoding_df.shape)

****************************************************************************************************
********************** Part1 1: Parsed Raw File ******************************************
****************************************************************************************************

,LineId,Label,Id,Date,Code1,Time,Code2,Component1,Component2,Level,Content,EventId,EventTemplate
0,1,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.363779,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
1,2,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.527847,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
2,3,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.675872,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
3,4,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.823719,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected
4,5,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.982731,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,3aa50e45,instruction cache parity error corrected

Shape of Parsed Raw File: (4713493, 13)

****************************************************************************************************
********************** Part 2:  Input Data with Features ******************************************
****************************************************************************************************

,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count,EventId_1,EventId_2
4,2005-06-03 16:00:00,4,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0,228,228
5,2005-06-03 16:05:00,5,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0,729,987
6,2005-06-03 16:10:00,6,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0,734,430
7,2005-06-03 16:15:00,7,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0,987,987
8,2005-06-03 16:25:00,9,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0,95,504

Shape of Encoded File with Features: (14537, 35451)

****************************************************************************************************
********************** Part 3: Event_ID to Template Mapping ******************************************
****************************************************************************************************

,EventId,EventTemplate,Occurrences
0,3aa50e45,instruction cache parity error corrected,105924
1,b9250ad9,MidplaneSwitchController performing bit sparing on R<*>-M<*>-L<*>-U<*>-C bit <*>,964
2,fc5f0940,generating core.<*>,1706751
3,1840cbfe,"<*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*>",33939
4,828a502b,<*> <*> <*> error(s) (dcr <*>) detected and corrected,5040

Shape of Event_ID to Template Mapping: (1000, 3)

****************************************************************************************************
********************** Part 4:  Event_ID to Encoding Mapping ******************************************
****************************************************************************************************

    EventId  EncodedValue
0  0025df56             0
1  0045c3a8             1
2  004a68ba             2
3  00980b01             3
4  00d49120             4

Shape of Event_ID to Encoding Mapping: (1000, 2)

---

# <font color = grey>Load new recon files for analysis

In [6]:
import os
import pandas as pd
import numpy as np
import random
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from datetime import datetime

# Parameters
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04A.Local_Data_Files'
input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
output_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files/20240714_Match_Sequence_Test_Recon'

# Generate timestamp and serial number
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
serial_number = "0001"  # You can increment this for each run
file_prefix = f"20240714_221127_non_overlap_full_test"

# Load and display a sample from the saved train and test data
X_train_sample = np.load(f"{output_dir}/{file_prefix}_X_train.npy")
y_train_sample = np.load(f"{output_dir}/{file_prefix}_y_train.npy")
indices_train_sample = np.load(f"{output_dir}/{file_prefix}_indices_train.npy")

X_test_sample = np.load(f"{output_dir}/{file_prefix}_X_test.npy")
y_test_sample = np.load(f"{output_dir}/{file_prefix}_y_test.npy")
indices_test_sample = np.load(f"{output_dir}/{file_prefix}_indices_test.npy")

print("Sample data from X_train:")
print(X_train_sample[:1])

print("Sample data from y_train:")
print(y_train_sample[:10])

print("Sample indices from training set:")
print(indices_train_sample[:10])

print("Sample data from X_test:")
print(X_test_sample[:1])

print("Sample data from y_test:")
print(y_test_sample[:10])

print("Sample indices from test set:")
print(indices_test_sample[:10])

print("Min and Max sequence indices for training set:")
print("Min:", indices_train_sample.min(), "Max:", indices_train_sample.max())

print("Min and Max sequence indices for test set:")
print("Min:", indices_test_sample.min(), "Max:", indices_test_sample.max())

# Print the shape of the original file
encoded_feature_input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
encoded_feature_input_file_df = pd.read_parquet(encoded_feature_input_file)
display(encoded_feature_input_file_df.iloc[:, :20].head())
print("Shape of Encoded File with Features:", encoded_feature_input_file_df.shape)

Sample data from X_train:
[[[ 4.00000000e+00  4.16888954e-01  4.90000000e+01 ... -1.53296629e+02
   -1.72384610e+02  6.73044307e+01]
  [ 5.00000000e+00 -2.07950176e-01  1.69000000e+02 ...  1.61375315e+02
    2.29718942e+02  8.70463488e+01]
  [ 6.00000000e+00  4.16888954e-01  8.00000000e+01 ...  2.02481490e+01
    3.49018957e+01  4.92429082e+01]
  ...
  [ 3.00000000e+01 -3.64159959e-01  1.35000000e+02 ... -1.56895977e+02
   -2.48404381e+02 -1.34980763e+02]
  [ 3.20000000e+01  2.60679172e-01  8.00000000e+01 ...  2.09232204e+02
    2.54553534e+02 -6.90262277e+01]
  [ 3.80000000e+01  2.60679172e-01  8.00000000e+01 ... -1.80357489e+00
   -3.50372973e+01 -1.20884282e+02]]]
Sample data from y_train:
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Sample indices from training set:
[[  0  23]
 [ 23  46]
 [ 46  69]
 [ 69  92]
 [ 92 115]
 [115 138]
 [138 161]
 [161 184]
 [184 207]
 [207 230]]
Sample data from X_test:
[[[ 4.55100000e+04 -3.64159959e-01  1.10000000e+01 ... -6.03386704e+01
   -7.63430651e+01  2.76562845e+01]
  [ 4.55140000e+04  1.04469389e-01  8.00000000e+01 ... -1.03639051e+02
   -1.36116477e+02  1.60575016e+01]
  [ 4.55190000e+04 -3.64159959e-01  4.10000000e+01 ... -6.49000767e+01
   -1.05809419e+02 -6.46902538e+01]
  ...
  [ 4.55720000e+04  4.16888954e-01  8.00000000e+01 ... -3.95672762e+01
   -1.02867421e+02 -1.92895632e+02]
  [ 4.55780000e+04 -3.64159959e-01  1.68000000e+02 ... -3.82875507e+01
   -4.59029017e+01  3.35630721e+01]
  [ 4.55800000e+04 -3.64159959e-01  5.00000000e+01 ... -3.82875507e+01
   -4.59029017e+01  3.35630721e+01]]]
Sample data from y_test:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Sample indices from test set:
[[11615 11638]
 [11638 11661]
 [11661 11684]
 [11684 11707]
 [11707 11730]
 [11730 11753]
 [11753 11776]
 [11776 11799]
 [11799 11822]
 [11822 11845]]
Min and Max sequence indices for training set:
Min: 0 Max: 11615
Min and Max sequence indices for test set:
Min: 11615 Max: 14536

,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count,EventId_1,EventId_2
4,2005-06-03 16:00:00,4,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0,228,228
5,2005-06-03 16:05:00,5,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0,729,987
6,2005-06-03 16:10:00,6,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0,734,430
7,2005-06-03 16:15:00,7,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0,987,987
8,2005-06-03 16:25:00,9,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0,95,504

Shape of Encoded File with Features: (14537, 35451)

# <font color = blue> Enhance Original Input File with Sequence Info

In [9]:
import pandas as pd
from datetime import datetime

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04A.Local_Data_Files'
input_file = f"{data_dir}/20240709_full_more_new_features_v1.00.parquet"
output_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'

# Load data
encoded_feature_input_file_df = pd.read_parquet(input_file)

# Create new columns
seq_num = encoded_feature_input_file_df.index
train_test = ['Train' if x <= 11614 else 'Test' for x in seq_num]

# Insert the new columns at the beginning
encoded_feature_input_file_df.insert(0, 'Seq_Num', seq_num)
encoded_feature_input_file_df.insert(1, 'Train_Test', train_test)

# Save the new DataFrame to a parquet file
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_file = f"{output_dir}/{timestamp}_orig_input_w_seq_mapping_master.parquet"

encoded_feature_input_file_df.to_parquet(output_file, index=False)

print(f"New file saved to {output_file}")

# Display the first 20 columns of the first few rows to verify
display(encoded_feature_input_file_df.iloc[:, :20].head())

New file saved to /home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files/20240714_225943_orig_input_w_seq_mapping_master.parquet

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
4,4,Train,2005-06-03 16:00:00,4,0,6,228,6,0.171708,16,4,465,35431,913.0,0.012903,0,0.000000,0.171708,4895.0,18.0
5,5,Train,2005-06-03 16:05:00,5,0,2,987,2,0.598270,16,4,7,35433,465.0,0.285714,0,0.171708,0.426562,4257.0,19.0
6,6,Train,2005-06-03 16:10:00,6,0,6,399,18,0.655243,16,4,81,35431,7.0,0.222222,0,0.598270,0.056973,2756.0,23.0
7,7,Train,2005-06-03 16:15:00,7,0,5,328,6,1.039660,16,4,66,35431,81.0,0.090909,0,0.655243,0.384418,1532.0,25.0
8,8,Train,2005-06-03 16:25:00,9,0,4,399,3,0.895333,16,4,14,35433,66.0,0.214286,0,1.039660,-0.144328,633.0,28.0

In [12]:
import pandas as pd

# Paths
data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
input_file = f"{data_dir}/20240714_225943_orig_input_w_seq_mapping_master.parquet"

# Load data
encoded_feature_input_file_df = pd.read_parquet(input_file)

# Display records from sequence 11600 to 11630 with only the first 20 columns
records_11600_to_11630 = encoded_feature_input_file_df.iloc[11600:11631, :20]
display(records_11600_to_11630)

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
11600,11604,Train,2005-11-08 13:50:00,45482,0,1,738,0,0.000000,13,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1043.0,12.0
11601,11605,Train,2005-11-08 14:00:00,45484,0,1,176,0,0.000000,14,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1036.0,12.0
11602,11606,Train,2005-11-08 14:10:00,45486,0,1,68,0,0.000000,14,1,13,35433,1.0,0.000000,0,0.000000,0.000000,1048.0,12.0
11603,11607,Train,2005-11-08 14:20:00,45488,0,1,68,0,0.000000,14,1,1,35433,13.0,0.000000,0,0.000000,0.000000,17.0,10.0
11604,11608,Train,2005-11-08 14:30:00,45490,0,3,108,2,0.483611,14,1,2910,35433,1.0,0.000687,0,0.000000,0.483611,2926.0,12.0
11605,11609,Train,2005-11-08 14:35:00,45491,0,2,108,1,0.029707,14,1,1714,35433,2910.0,0.000583,0,0.483611,-0.453904,4639.0,13.0
11606,11610,Train,2005-11-08 14:40:00,45492,0,2,108,1,0.348832,14,1,4608,35433,1714.0,0.000217,0,0.029707,0.319125,9246.0,14.0
11607,11611,Train,2005-11-08 15:05:00,45497,0,1,638,0,0.000000,15,1,16,35433,4608.0,0.000000,0,0.348832,-0.348832,9249.0,14.0
11608,11612,Train,2005-11-08 15:10:00,45498,0,2,68,1,0.693147,15,1,16,35433,16.0,0.062500,0,0.000000,0.693147,9264.0,15.0
11609,11613,Train,2005-11-08 15:15:00,45499,0,1,638,0,0.000000,15,1,8,35433,16.0,0.000000,0,0.693147,-0.693147,6362.0,13.0
11610,11614,Train,2005-11-08 15:25:00,45501,0,1,763,0,0.000000,15,1,3,35433,8.0,0.000000,0,0.000000,0.000000,4651.0,12.0
11611,11615,Test,2005-11-08 15:35:00,45503,0,1,638,0,0.000000,15,1,8,35433,3.0,0.000000,0,0.000000,0.000000,51.0,11.0
11612,11616,Test,2005-11-08 15:40:00,45504,0,1,68,0,0.000000,15,1,8,35433,8.0,0.000000,0,0.000000,0.000000,43.0,11.0
11613,11617,Test,2005-11-08 15:55:00,45507,0,1,68,0,0.000000,15,1,1,35433,8.0,0.000000,0,0.000000,0.000000,28.0,10.0
11614,11618,Test,2005-11-08 16:05:00,45509,0,1,68,0,0.000000,16,1,8,35433,1.0,0.000000,0,0.000000,0.000000,28.0,10.0
11615,11619,Test,2005-11-08 16:10:00,45510,0,1,68,0,0.000000,16,1,1,35433,8.0,0.000000,0,0.000000,0.000000,26.0,10.0
11616,11620,Test,2005-11-08 16:30:00,45514,0,4,399,9,1.251989,16,1,15,35433,1.0,0.600000,1,0.000000,1.251989,33.0,13.0
11617,11621,Test,2005-11-08 16:55:00,45519,0,1,176,0,0.000000,16,1,1,35433,15.0,0.000000,0,1.251989,-1.251989,26.0,13.0
11618,11622,Test,2005-11-08 17:25:00,45525,1,2,74,1,0.693147,17,1,1024,35433,1.0,0.000977,0,0.000000,0.693147,1049.0,14.0
11619,11623,Test,2005-11-08 17:30:00,45526,0,1,176,0,0.000000,17,1,1,35433,1024.0,0.000000,0,0.693147,-0.693147,1042.0,14.0
11620,11624,Test,2005-11-08 17:45:00,45529,0,1,68,0,0.000000,17,1,1,35433,1.0,0.000000,0,0.000000,0.000000,1042.0,14.0
11621,11625,Test,2005-11-08 18:25:00,45537,0,3,95,2,1.098612,18,1,3,35433,1.0,0.666667,1,0.000000,1.098612,1030.0,13.0
11622,11626,Test,2005-11-08 18:35:00,45539,0,1,68,0,0.000000,18,1,2,35433,3.0,0.000000,0,1.098612,-1.098612,1031.0,13.0
11623,11627,Test,2005-11-08 18:40:00,45540,0,1,228,0,0.000000,18,1,1,35433,2.0,0.000000,0,0.000000,0.000000,8.0,12.0
11624,11628,Test,2005-11-08 18:50:00,45542,0,2,68,1,0.500402,18,1,10,35433,1.0,0.100000,0,0.000000,0.500402,17.0,13.0
11625,11629,Test,2005-11-08 19:00:00,45544,0,6,399,27,0.427570,19,1,300,35426,10.0,0.090000,0,0.500402,-0.072833,316.0,18.0
11626,11630,Test,2005-11-08 19:05:00,45545,0,2,68,1,0.095030,19,1,52,35433,300.0,0.019231,0,0.427570,-0.332539,365.0,17.0
11627,11631,Test,2005-11-08 19:15:00,45547,0,1,68,0,0.000000,19,1,51,35433,52.0,0.000000,0,0.095030,-0.095030,414.0,17.0
11628,11632,Test,2005-11-08 19:20:00,45548,0,4,68,3,0.275593,19,1,54,35433,51.0,0.055556,0,0.000000,0.275593,467.0,20.0
11629,11633,Test,2005-11-08 19:25:00,45549,0,1,763,0,0.000000,19,1,3,35433,54.0,0.000000,0,0.275593,-0.275593,460.0,19.0
11630,11634,Test,2005-11-08 19:45:00,45553,0,1,606,0,0.000000,19,1,1,35433,3.0,0.000000,0,0.000000,0.000000,161.0,14.0

In [13]:
# Display the first 20 columns of the first few rows to verify
display(encoded_feature_input_file_df.iloc[:, :20].tail())

,Seq_Num,Train_Test,time_start,time_start_int,Class,unique_events,most_frequent_event,transitions,entropy,hour_of_day,day_of_week,event_count,top_event_frequency,prev_event_count,transition_rate,high_transition_rate,prev_entropy,entropy_change,rolling_event_count,rolling_unique_event_count
14532,14536,Test,2006-01-04 07:35:00,61823,0,1,606,0,0.000000,7,2,1,35433,4.0,0.0,0,0.693147,-0.693147,53.0,18.0
14533,14537,Test,2006-01-04 07:40:00,61824,0,6,156,5,1.609438,7,2,10,35431,1.0,0.5,0,0.000000,1.609438,48.0,18.0
14534,14538,Test,2006-01-04 07:45:00,61825,0,2,193,1,0.693147,7,2,2,35433,10.0,0.5,0,1.609438,-0.916291,49.0,19.0
14535,14539,Test,2006-01-04 07:50:00,61826,0,3,156,2,1.039721,7,2,4,35433,2.0,0.5,0,0.693147,0.346574,21.0,19.0
14536,14540,Test,2006-01-04 08:00:00,61828,1,1,99,0,0.000000,8,2,8,35433,4.0,0.0,0,1.039721,-1.039721,25.0,18.0

___
# <font color = blue> Part 2. Run Inference for Multiple Records with Flask App

In [ ]:
# import requests
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

# # Load your test data
# data_dir = '/home/ubuntu/efs-w210-capstone-ebs/04C.Local_Inference_Eval_Files'
# file_prefix = "20240714_062624_non_overlap_full_test"  # Replace with your actual file prefix
# X_test = np.load(f"{data_dir}/{file_prefix}_X_test.npy")
# y_test = np.load(f"{data_dir}/{file_prefix}_y_test.npy")

# # Prepare the data for the request
# data = {'X_test': X_test.tolist()}

# # Send a request to the server
# response = requests.post('http://0.0.0.0:5000/predict', json=data)

# # Process the response
# predictions = np.array(response.json()['predictions'])

# # Print first 10 predictions and actual labels
# print("First 10 predictions:", predictions[:10])
# print("First 10 actual labels:", y_test[:10])

# # Print the records with predicted and actual labels
# results_df = pd.DataFrame({
#     'Record': range(len(predictions)),
#     'Predicted Label': predictions.flatten(),
#     'Actual Label': y_test.flatten()
# })

# print(f"Results for all records:")
# print(results_df)

# # Calculate metrics
# conf_matrix = confusion_matrix(y_test, predictions)
# precision = precision_score(y_test, predictions, zero_division=0)
# recall = recall_score(y_test, predictions, zero_division=0)
# accuracy = accuracy_score(y_test, predictions)
# f1 = f1_score(y_test, predictions, zero_division=0)
# tn, fp, fn, tp = conf_matrix.ravel()

# metrics_df = pd.DataFrame({
#     'Metric': ['Accuracy', 'Precision (Class 1)', 'Recall (Class 1)', 'F1 Score', 'True Positives', 'False Positives', 'True Negatives', 'False Negatives'],
#     'Value': [accuracy, precision, recall, f1, tp, fp, tn, fn]
# })

# print("==================================================")
# print("Metrics:")
# print(metrics_df)

# # Plot the confusion matrix
# plt.figure(figsize=(10, 7))
# sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
# plt.xlabel('Predicted')
# plt.ylabel('Actual')
# plt.title('Confusion Matrix')
# plt.show()